---
- name: Sanity checks
  import_tasks: checks.yml

- name: Configure mandatory and unwanted packages
  import_tasks: _packages.yml

- name: Configure hostname, locale, timezone and sysctl
  import_tasks: _system.yml

- name: Configure ansible local facts
  import_tasks: _local_facts.yml

- name: Configure ntp
  import_tasks: _ntp.yml

- name: Configure preferences
  import_tasks: _preferences.yml

- name: Configure ssh client and server
  import_tasks: _ssh.yml

- name: Configure connection banner
  import_tasks: _banner.yml

- meta: flush_handlers