# tasks/dovecot.yml -- Install and configure Dovecot
---
- name: Dovecot - install system packages
  apt:
    name: "{{ mailserver_dovecot_packages }}"

- name: Dovecot - add dovecot user to ssl-cert group
  user:
    name: dovecot
    append: yes
    groups:
      - ssl-cert

- name: Dovecot - apply thunderbird fix
  lineinfile:
    path: "{{ dovecot_config_dir }}/20-imap.conf"
    regexp: '^#imap_client_workarounds'
    line: 'imap_client_workarounds = tb-extra-mailbox-sep'
  notify: Restart dovecot service

- name: Dovecot - configure authentication mechanisms
  template:
    src: dovecot-auth.conf.j2
    dest: "{{ dovecot_config_dir }}/10-auth.conf"
  notify: Restart dovecot service

- name: Dovecot - configure mail mechanisms
  template:
    src: dovecot-mail.conf.j2
    dest: "{{ dovecot_config_dir }}/10-mail.conf"
  notify: Restart dovecot service

- name: Dovecot - configure master mechanisms
  template:
    src: dovecot-master.conf.j2
    dest: "{{ dovecot_config_dir }}/10-master.conf"
  notify: Restart dovecot service

- name: Dovecot - configure ssl
  template:
    src: dovecot-ssl.conf.j2
    dest: "{{ dovecot_config_dir }}/10-ssl.conf"
  notify: Restart dovecot service

- name: Dovecot - enable service
  service:
    name: "{{ mailserver_dovecot_service }}"
    state: started
    enabled: true

- name: "Set mailserver password"
  lineinfile:
    regex: >-
      ^{{ item.email }}.*
    line: >-
      {{ item.email }}:{CRYPT}{{ ansible_local.system_users_password_hash[item.system_user].bcrypt }}:::
    dest: /etc/dovecot/users
    create: yes
  loop: "{{ postfix_virtual_mailboxes }}"
  when:
    - item.system_user is defined
    - item.system_user in ansible_local.system_users_password_hash.keys() | default([])

- meta: flush_handlers