---
- name: Spamassassin - install system packages
  apt:
    name: "{{ mailserver_spamassassin_packages }}"

- name: Spamassassin - configure daemon
  template:
    src: "spamassassin.local.cf.j2"
    dest: "/etc/spamassassin/local.cf"
  notify: Restart spamassassin service

- name: Spamassassin - configure plugins
  template:
    src: "spamassassin.v310.pre.j2"
    dest: "/etc/mail/spamassassin/v310.pre"
  notify: Restart spamassassin service

- name: Spamassassin - enable service
  systemd:
    name: spamassassin
    state: started
    enabled: yes
