---
_system_users_uninstall: "{{ system_users_uninstall | default(false) | bool }}"

system_users_default_shell: "/bin/bash"
system_users_default_home: "/home/{{ current_user.uname }}"
system_users_local_passwords_dir: "{{ local_secrets_dir }}/system_users/{{ inventory_hostname }}"

system_users_password: "{{ }}"
system_users_reserved:
  - uname: "radicale"
    uid: "59000"
  - uname: "mattermost"
    uid: "59001"

system_users_supported_hash:
  - sha512
  - bcrypt

system_users_prefered_hash: >-
  {{ system_users_local_passwords_dir }}/{{ current_user.uname }}.password.{{ ansible_local.system_base_pam.password_hash_policy }}

system_users_clear_password_file: "{{ system_users_local_passwords_dir }}/{{ item[0].uname }}.password"
system_users_hashed_password_file: "{{ system_users_local_passwords_dir }}/{{ item[0].uname }}.password.{{ item[1] }}"