---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
# configuration variables
    tf_stack: scw
    # workspace: 
# utils variables    
    project_dir: "{{ (playbook_dir + '/..') | realpath }}" 
    tf_stack_dir: "{{ project_dir }}/terraform/{{ tf_stack }}"

    ssh_private_key_file: "{{ project_dir }}/keys/{{ workspace }}.key"
    ssh_public_key_file: "{{ ssh_private_key_file }}.pub"
    
    ready_host_name: "{{ workspace }}"
    raw_host_name: "raw_{{ workspace }}"
    clan_name: "{{ tf_stack }}_{{ workspace }}_clan"
    ready_host_vars_dir: "{{ project_dir }}/host_vars/{{ workspace }}"
    ready_host_vars_file: "{{ ready_host_vars_dir }}/tf_vars.yml"
    ready_srv_host_vars_file: "{{ ready_host_vars_dir }}/services.yml"

    tfstate_dir: "{{ project_dir }}/tfstates"
    raw_host_vars_dir: "{{ project_dir }}/host_vars/raw_{{ workspace }}"
    raw_host_vars_file: "{{ raw_host_vars_dir }}/tf_vars.yml"

  tasks:
    - name: Sanity checks
      assert:
        that:
          - workspace is defined
          - workspace != 'default'
        msg: "'workspace' must be defined and not 'default'"

    - name: Directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ tfstate_dir }}"
        - "{{ tfstate_dir }}/{{ workspace }}"
        - "{{ project_dir }}/keys"

    - name: Create a dedicated keypair
      openssh_keypair:
        path: "{{ ssh_private_key_file }}"
        type: ed25519

    - name: "Apply workspace {{ workspace }} on {{ tf_stack }}"
      terraform:
        project_path: "{{ tf_stack_dir }}"
        state: present
        force_init: true
        workspace: "{{ workspace }}"
        variables:
          ssh_public_key_file: "{{ ssh_public_key_file }}"
      register: tf_apply

    - set_fact:
        public_ipv4: "{{ tf_apply.outputs.ipv4.value }}"
        public_ipv6: "{{ tf_apply.outputs.ipv6.value }}"
        raw_ssh_user: "{{ tf_apply.outputs.raw_ssh_user.value }}"

    - name: Create host vars directory
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ raw_host_vars_dir }}"
        - "{{ ready_host_vars_dir }}"

    - name: Render terraform host vars
      copy:
        dest: "{{ item }}"
        content: |
          ---
          workspace: "{{ workspace }}"
          caretaker_authorized_key_files:
            - "{{ ssh_public_key_file }}"
          public_ipv4: "{{ tf_apply.outputs.ipv4.value }}"
          public_ipv6: "{{ tf_apply.outputs.ipv6.value }}"
      loop:
        - "{{ raw_host_vars_file }}"
        - "{{ ready_host_vars_file }}"

    - name: Render terraform host vars
      template:
        src: host_vars.yml.j2
        dest: "{{ ready_srv_host_vars_file }}"

    - name: Add raw and ready host definitions to ssh config
      blockinfile:
        path: "{{ project_dir }}/ssh.cfg"
        state: present
        create: yes
        marker: "# {mark} -- playbooks/create_cloud_host.yml -- {{ workspace }}"
        block: |
          Host {{ raw_host_name }} 
            Hostname {{ public_ipv4 }}
            User {{ raw_ssh_user }}
            IdentityFile {{ ssh_private_key_file }}
            IdentitiesOnly yes
            StrictHostKeyChecking no

          Host {{ ready_host_name }}
            Hostname {{ public_ipv4 }}
            User caretaker
            IdentityFile {{ ssh_private_key_file }}
            IdentitiesOnly yes
            StrictHostKeyChecking no

    - name: Add raw and ready host definitions to inventory group
      blockinfile:
        path: "{{ project_dir }}/hosts"
        state: present
        create: yes
        marker: "# {mark} -- playbooks/create_cloud_host.yml -- {{ workspace }}"
        block: |
          [{{ clan_name }}]
          {{ raw_host_name }}
          {{ ready_host_name }}    

    - name: Link created host group to 'clans' group in inventory
      lineinfile:
        path: "{{ project_dir }}/hosts"
        state: present
        line: >-
          {{ clan_name }}
        insertafter: >-
          \[clans:children\]

    - meta: refresh_inventory

- import_playbook: "{{ playbook_dir }}/provision_ansible_user.yml"
  vars:
    scope: "raw_{{ workspace }}"

- hosts: "{{ workspace }}"
  become: yes
  tasks:
    - ping: